---
language: python

install:
  - pip install mkdocs
  - pip install mkdocs-cinder
  - pip install ansible-lint

script:
  - mkdocs build
  - ansible-lint charjabox.yml

deploy:
  provider: pages
  skip_cleanup: true
  local-dir: site/
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
