---
- name: general setup
  hosts: all
  become: true
  gather_facts: "True"
  vars_files:
    - "settings/charjabox_general.yml"
  tags: general
  roles:
    - charjabox_general

- name: smb
  hosts: all
  become: true
  gather_facts: "True"
  vars_files:
    - "settings/charjabox_general.yml"
    - "settings/smb.yml"
  roles:
    - role: bertvv.samba
      when: smb_enabled
    - role: smb
      when: smb_enabled

- name: portainer
  hosts: all
  become: true
  gather_facts: "True"
  vars_files:
    - "settings/charjabox_general.yml"
    - "settings/portainer.yml"
  tags: portainer
  roles:
    - role: portainer
      when: portainer_enabled

- name: plex
  hosts: all
  become: true
  gather_facts: "True"
  vars_files:
    - "settings/charjabox_general.yml"
    - "settings/plex.yml"
  tags: plex
  roles:
    - role: plex
      when: plex_enabled
