---
- hosts: "{{ charjabox_host | default('all') }}"
  become: true
  vars:
    docker_install_compose: true
    docker_compose_path: /usr/bin/docker-compose
    apps:
      - airsonic
      - bazarr
      - bind
      - bitwarden_rs
      - dokuwiki
      - firefly
      - gitea
      - heimdall
      - jackett
      - jellyfin
      - lancache
      - lidarr
      - miniflux
      - nextcloud
      - nginx
      - plex
      - portainer
      - radarr
      - rtorrent
      - sonarr
      - timemachine
      - traefik
      - tautulli

  pre_tasks:
    - include: tasks/prep.yml
      tags: always
    - include: tasks/general.yml
      tags: always

  roles:
    - role: bertvv.samba
      when: smb_enabled
      tags: smb
    - role: geerlingguy.docker
      tags: always
    - role: charjabox_deploy
      tags: deploy

  tasks:
    - include: tasks/smb.yml
      when: smb_enabled
