---
- hosts: all
  become: true
  vars:
    docker_install_compose: true
    docker_compose_path: /usr/bin/docker-compose

  pre_tasks:
    - name: include defaults
      include_vars:
        dir: "settings/defaults"
      tags: always
    - name: include vars
      include_vars:
        dir: "settings/{{ charjabox_settings_path }}"
      tags: always

  roles:
    - role: charjabox_general
      tags: general
    - role: bertvv.samba
      when: smb_enabled
      tags: smb
    - role: smb
      when: smb_enabled
      tags: smb
    - role: geerlingguy.docker
      tags: always
    - role: nginx
      when: nginx_enabled
      tags: nginx
    - role: portainer
      when: portainer_enabled
      tags: portainer
    - role: plex
      when: plex_enabled
      tags: plex
    - role: jellyfin
      when: jellyfin_enabled
      tags: jellyfin
    - role: heimdall
      when: heimdall_enabled
      tags: heimdall
    - role: bind
      when: bind_enabled
      tags: bind
    - role: firefly
      when: firefly_enabled
      tags: firefly
    - role: lancache
      when: lancache_enabled
      tags: lancache
    - role: dokuwiki
      when: dokuwiki_enabled
      tags: dokuwiki
    - role: timemachine
      when: timemachine_enabled
      tags: timemachine
    - role: gitea
      when: gitea_enabled
      tags: gitea
    - role: jackett
      when: jackett_enabled
      tags: jackett
    - role: radarr
      when: radarr_enabled
      tags: radarr
    - role: sonarr
      when: sonarr_enabled
      tags: sonarr
    - role: lidarr
      when: lidarr_enabled
      tags: lidarr
    - role: rtorrent
      when: rtorrent_enabled
      tags: rtorrent
