---
- hosts: "{{ charjabox_host | default('all') }}"
  become: true
  vars:
    docker_install_compose: true
    docker_compose_path: /usr/bin/docker-compose
    apps:
      - airsonic
      - bazarr
      - bind
      - bitwarden_rs
      - dokuwiki
      - firefly
      - gitea
      - heimdall
      - jackett
      - jellyfin
      - lancache
      - lidarr
      - miniflux
      - nextcloud
      - nginx
      - plex
      - portainer
      - radarr
      - rtorrent
      - sonarr
      - timemachine
      - traefik

  pre_tasks:
    - name: include defaults
      include_vars:
        dir: "settings/defaults"
      tags: always
    - name: include vars
      include_vars:
        dir: "settings/{{ charjabox_settings_path }}"
      tags: always
    - include: tasks/prep.yml
      tags: always

  roles:
    - role: charjabox_general
      tags: general
    - role: bertvv.samba
      when: smb_enabled
      tags: smb
    - role: geerlingguy.docker
      tags: always
    - role: charjabox_deploy
      tags: deploy

  tasks:
    - include: tasks/smb.yml
      when: smb_enabled
