---
- name: include defaults
  include_vars:
    dir: "../settings/defaults"

- name: include vars
  include_vars:
    dir: "../settings/{{ charjabox_settings_path }}"

- name: Initialize an empty list for enabled apps
  set_fact:
    apps_enabled: []

- name: Initialize an empty list for disabled apps
  set_fact:
    apps_disabled: []

- name: Append enabled apps to list
  set_fact:
    apps_enabled: "{{ apps_enabled + [  item  ] }}"
  loop: "{{ apps }}"
  when: 'lookup("vars", item + "_enabled")'

- name: Append disabled apps to list
  set_fact:
    apps_disabled: "{{ apps_disabled + [  item  ] }}"
  loop: "{{ apps }}"
  when: 'not lookup("vars", item + "_enabled")'

- name: Make sure disabled apps are not running
  systemd:
    name: "{{ item }}"
    enabled: false
    daemon-reload: true
    state: stopped
  loop: "{{ apps_disabled }}"
  ignore_errors: true # This is needed so the playbook doesn't fail because of non-existing services
