---
- name: create firefly directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ firefly_config_directory }}"
    - "{{ firefly_config_directory }}/export"
    - "{{ firefly_config_directory }}/upload"
    - "{{ firefly_config_directory }}/db"

- name: create firefly docker-compose directory
  file:
    path: "{{ docker_compose_dir }}/firefly"
    state: directory

- name: copy docker-compose.yml for firefly
  template:
    src: docker-compose.firefly.yml.j2
    dest: "{{ docker_compose_dir }}/firefly/docker-compose.firefly.yml"

- name: configure firefly systemd service
  template:
    src: firefly.service.j2
    dest: /etc/systemd/system/firefly.service

- name: start firefly
  systemd:
    name: firefly
    enabled: "yes"
    daemon-reload: "yes"
    state: started