---
- name: create bazarr directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bazarr_config_directory }}"

- name: create bazarr docker-compose directory
  file:
    path: "{{ docker_compose_dir }}/bazarr"
    state: directory

- name: copy docker-compose.yml for bazarr
  template:
    src: docker-compose.bazarr.yml.j2
    dest: "{{ docker_compose_dir }}/bazarr/docker-compose.bazarr.yml"

- name: configure bazarr systemd service
  template:
    src: bazarr.service.j2
    dest: /etc/systemd/system/bazarr.service

- name: start bazarr
  systemd:
    name: bazarr
    enabled: "yes"
    daemon-reload: "yes"
    state: started
