---
- hosts: localhost
  connection: local
  gather_facts: false
  vars_prompt:
    - name: "app"
      prompt: "What should the app be called?"
      private: false

  tasks:
    - name: Create directories for new app {{ app }}
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
      with_items:
        - { path: "{{ playbook_dir }}/../roles/{{ app }}/templates", state: directory }
        - { path: "{{ playbook_dir }}/../roles/charjabox_deploy/templates/docker-compose.{{ app }}.yml.j2", state: touch }
        - { path: "{{ playbook_dir }}/../settings/defaults/{{ app }}.yml", state: touch }
