---
- name: create traefik directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ traefik_config_directory }}"

- name: create traefik docker-compose directory
  file:
    path: "{{ docker_compose_dir }}/traefik"
    state: directory

- name: copy docker-compose.yml for traefik
  template:
    src: docker-compose.traefik.yml.j2
    dest: "{{ docker_compose_dir }}/traefik/docker-compose.traefik.yml"

- name: upload traefik.yml template
  template:
    src: traefik.yml.j2
    dest: "{{ traefik_config_directory }}/traefik.yml"

- name: configure traefik systemd service
  template:
    src: traefik.service.j2
    dest: /etc/systemd/system/traefik.service

- name: start traefik
  systemd:
    name: traefik
    enabled: "yes"
    daemon-reload: "yes"
    state: started
