---
- name: install dependencies
  apt:
    name: "{{charjabox_packages}}"    
  tags:
    - dependencies

- name: set hostname
  hostname:
    name: "{{charjabox_hostname}}"

- name: configure timezone
  timezone:
    name: "{{ charjabox_timezone }}"
